name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --deploy --ignore-pipfile
        pipenv run pytest --cache-clear --cov=app tests/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
