name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils
        pip install --upgrade pip
    - name: install python dependencies
      run: |
        pip install pipenv
        pipenv install --system --deploy --ignore-pipfile
        pipenv install --dev --system --deploy --ignore-pipfile
        pip install codecov
    - name: run tests
      run: pytest -v tests/ --cov=transform --cov-report html
    - name: get coverage
      run: codecov
